app/models.py
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from app import db, login

@login.user_loader
def load_user(user_id):
    return User.query.get(user_id)

class User(db.Model, UserMixin):
    user_id=db.Column(db.Integer, primary_key=True)
    username=db.Column(db.String, unique=True)
    email=db.Column(db.String, unique=True)
    password=db.Column(db.String)
    cars=db.relationship('Car', backref='author', lazy=True)

    def __repr__(self):
        return f'User: {self.username}'

    def commit(self):
        db.session.add(self)
        db.session.commit()

    def hash_password(self, password):
        return generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password, password)
    
    def get_id(self):
        return str(self.user_id)

class Car(db.Model):
    car_id=db.Column(db.Integer, primary_key=True)
    brand=db.Column(db.String(50))
    model=db.Column(db.String(50))
    year=db.Column(db.Integer)
    description=db.Column(db.String(200))
    user_id=db.Column(db.Integer, db.ForeignKey('user.user_id'), nullable=False)

    def __repr__(self):
        return f'Car: {self.brand}'

    def commit(self):
        db.session.add(self)
        db.session.commit()

app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Email

class RegisterForm(FlaskForm):
    username = StringField('username', validators=[DataRequired()])
    email = StringField('email', validators=[DataRequired(), Email()])
    password = PasswordField('password', validators=[DataRequired()])
    submit = SubmitField('Register')

class SigninForm(FlaskForm):
    username = StringField('username', validators=[DataRequired()])
    password = PasswordField('password', validators=[DataRequired()])
    submit = SubmitField('Sign In')

class CarForm(FlaskForm):
    brand =StringField('brand', validators=[DataRequired()])
    model=StringField('model', validators=[DataRequired()])
    year=StringField('year', validators=[DataRequired()])
    description=StringField('desc')
    submit = SubmitField('Collect')

app/__init__.py
from flask import Flask
from config import Config
from flask_sqlalchemy import SQLAlchemy 
from flask_migrate import Migrate
from flask_login import LoginManager

app = Flask(__name__)
app.config.from_object(Config)
db = SQLAlchemy(app)
migrate = Migrate(app, db)
login = LoginManager(app)

from app.blueprints.main import bp as main_bp
app.register_blueprint(main_bp)

from app.blueprints.auth import bp as auth_bp
app.register_blueprint(auth_bp)

from app.blueprints.collection import bp as collection_bp
app.register_blueprint(collection_bp)

from app import models

app/blueprints/api/__init__.py
from flask import Blueprint

bp = Blueprint('api', __name__, url_prefix='/api')

from app.blueprints.api import routes, auth_routes

app/blueprints/api/routes.py
from flask import request, jsonify

from . import bp
from app.models import Car, User

# Receive all cars
@bp.get('/post')
def api_cars():
    result = []
    cars = Car.query.all()
    for car in cars:
        result.append(
            {
            'id': car.id,
            'brand': car.brand,
            'model': car.model,
            'year': car.year,
            'description': car.description,
            'author': car.user_id
            }
        )
    return jsonify(result), 200

# Receive Cars from single user
@bp.get('/post/<username>')
def user_cars(username):
    user = User.query.filter_by(username=username).first()
    if user:
        return jsonify([{
            'id': car.id,
            'brand': car.brand,
            'model': car.model,
            'year': car.year,
            'description': car.description
        }for car in user.cars]), 200
    return jsonify([{'message':'Invalid Username'}]), 404

# Send single car to the api database
@bp.get('/post/<id>')
def get_car(id):
    try:
        car = Car.query.get(id)
        return jsonify([{
            'id': car.id,
            'brand': car.brand,
            'model': car.models,
            'year': car.year,
            'description': car.description,
            'author': car.user_id

        }])
    except:
        return jsonify([{'message':'Invalid Post Id'}]), 404                                                                                                                                                      

app/blueprints/collection/__init__.py
from flask import Blueprint

bp = Blueprint('collection', __name__, url_prefix='/collection')

from . import routes

app/blueprints/collection/routes.py
from flask import render_template, flash, redirect, url_for

from app.models import Car
from flask_login import current_user, login_required
from . import bp

from app.models import Car, User
from app.forms import CarForm

@bp.route('/car', methods=['GET', 'POST'])
@login_required
def car():
    form=CarForm()
    if form.validate_on_submit():
        c = Car(brand=form.brand.data, model=form.model.data, year=form.year.data, description=form.description.data)
        c.user_id = current_user.user_id
        c.commit()
        flash(f'Car has registered to {c.author}')
        return redirect(url_for('collection.user_page', username=current_user.username))
    return render_template('inventory.j2', form=form)

@bp.route('/username/<username>')
@login_required
def user_page(username):
    user = User.query.filter_by(username=username).first()
    return render_template('user_page.j2', title=username, user=user)

app/blueprints/main/__init__.py
from flask import Blueprint

bp = Blueprint('main',__name__)

from app.blueprints.main import routes

app/blueprints/main/routes.py
from flask import render_template

from . import bp

@bp.route('/')
def home():
    return render_template('index.j2', title='Home')

@bp.route('/inventory')
def inventory():
    return render_template('about.j2')

app/templates/about.j2
{% extends "base.j2" %}
{% block content %}
    <p>Inventory page</p>
{% endblock %}

app/templates/base.j2
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    <title>Car Inventory</title>
</head>
<body>
{# nav bar #}
<nav class="container">
    <ul class="nav justify-content-end">
  <li class="nav-item">
    <a class="nav-link active" aria-current="page" href="{{url_for('main.home')}}">Home</a>
  </li>
  {% if not current_user.is_authenticated %}
  <li class="nav-item">
    <a class="nav-link" href="{{ url_for('auth.register') }}">Register</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{{ url_for('auth.signin') }}">Sign In</a>
  </li>
  {% else %}
  <li class="nav-item">
    <a class="nav-link" href="{{ url_for('collection.car') }}">Our Inventory</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{{ url_for('collection.user_page', username=current_user.username) }}">Your Space</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{{ url_for('auth.logout') }}">Log Out</a>
  </li>
  {% endif %}
</ul>
</nav>
{# end nav bar here #}
{% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
  <ul>
  {% for category, message in messages %}
    <li class="alert alert-{{ category }} alert-dismissible fade show" role="alert">{{ message }}
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </li>
  {% endfor %}
  </ul>
  {% endif %}
  {%  endwith %}
{% block content %} {% endblock %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
</body>
</html>

app/templates/index.j2
{% extends "base.j2" %}
{% block content %}
    <div class="hero-section">
        <h1 class="headline">Biggest car inventory in Dallas</h1>
        <img src="../static/images/undraw_To_the_moon_re_q21i.png" alt="hero picture" class="hero-img">
    </div>
{% endblock %}

app/templates/inventory.j2
{% extends "base.j2" %}

{% block content %}
  <h2>Post</h2>
  <form action="" method="post">
  {{ form.hidden_tag() }}
 <p>
    {{ form.brand.label }}<br>
    {{ form.brand(size=32) }}
 </p>
 <p>
    {{ form.model.label }}<br>
    {{ form.model(size=32) }}
    {% for error in form.brand.errors %}
      <span class="err-msg">{{ error }}</span>
    {% endfor %}
 </p>
 <p>
    {{ form.year.label }}<br>
    {{ form.year(size=32) }}
 </p>
 <p>
   {{ form.description.label }}<br>
   {{ form.description(size=32) }}
 </p>
 
 <p>{{ form.submit() }}</p>
</form>
{% endblock %}

app/templates/register.j2
{% extends "base.j2" %}
{% block content %}
   <form action="" method="POST" class="container">
 <h2>Register</h2>
 {{ form.hidden_tag() }}
 <p>
    {{ form.username.label }}<br>
    {{ form.username(size=32) }}
 </p>
 <p>
    {{ form.email.label }}<br>
    {{ form.email(size=32) }}
    {% for error in form.email.errors %}
      <span class="err-msg">{{ error }}</span>
    {% endfor %}
 </p>
 <p>
    {{ form.password.label }}<br>
    {{ form.password(size=32) }}
    {% for error in form.password.errors %}
      <span class="err-msg">{{ error }}</span>
    {% endfor %}
 </p>
 <p>{{ form.submit() }}</p>
</form>
{% endblock %}

app/templates/signin.j2
{% extends "base.j2" %}
{% block content %}
    <h2>Sign In</h2>
    <form action="" method="post">
    {{ form.hidden_tag() }}
     <p>
    {{ form.username.label }}<br>
    {{ form.username(size=32) }}
    </p>
    <p>
    {{ form.password.label }}<br>
    {{ form.password(size=32) }}
    {% for error in form.password.errors %}
      <span class="err-msg">{{ error }}</span>
    {% endfor %}
    </p>
     <p>{{ form.submit() }}</p>
    </form>
{% endblock %}

app/templates/user_page.j2
{% extends "base.j2" %}

{% block content %}
<h3>{{ user.username }}'s Page</h3>

{% for car in user.cars %}
  <p>{{ car.brand }} {{ car.model }} {{car.year}}</p>
{% endfor %}
{% endblock %}